services:
  io_tcpdf:
    class:  Io\TcpdfBundle\Helper\Configuration
    arguments:
      - @service_container
    calls:
      - [ setHelper, [ @io_tcpdf_helper ] ]

  io_tcpdf_helper:
    public: false
    class:  Io\TcpdfBundle\Helper\Tcpdf
    arguments:
      orientation: P
      unit:        mm
      format:      A4
      unicode:     true
      encoding:    UTF-8
      diskcache:   false
      pdfa:        false
